name: Main Branch Deployment and Tagging Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run unit/integration tests
        run: npm test
      - name: Run Playwright e2e tests
        run: npx playwright test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build_and_test
    # 如果 head_commit (最新的 commit 到 main) 的消息不包含 #skip，则部署
    if: >
      success() &&
      github.event.head_commit &&
      !contains(github.event.head_commit.message, '#skip')
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          # 确保此 action 等待部署成功

  tag_release:
    name: Bump version and Push Tag (on PR Merge after Deploy)
    runs-on: ubuntu-latest
    needs: deploy
    # 如果部署成功，并且是 PR 合并 (通过合并提交消息判断)，
    # 并且合并提交消息不包含 #skip，则打标签
    if: >
      success() &&
      github.event.head_commit &&
      startsWith(github.event.head_commit.message, 'Merge pull request #') &&
      !contains(github.event.head_commit.message, '#skip')
    permissions:
      contents: write
    steps:
      - name: Checkout code for tagging
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} # github.sha 在 push 事件中是 head_commit 的 SHA
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true